routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/
Auth::routes();
Route::middleware(['auth'])->group(function () {
    Route::post('/', 'RoleController@permissionGrant')->name('permissions.grant');
    Route::get('/', 'HomeController@index')->name('home');
    Route::get('/home', 'HomeController@index')->name('home');
    Route::resource('/board', 'TeamBoardController');
    Route::resource('/tribes', 'TribeController');
    Route::resource('/users', 'UserController');
    Route::resource('/roles', 'RoleController');
    Route::resource('/systems', 'SystemController');
    Route::get('/my_projects', 'ProjectController@myProjects')->name('projects.mine');
    Route::get('/projects/join/{user_id}/{project_id}', 'ProjectController@joinProject')->name('projects.join');
    Route::get('/projects/leave/{user_id}/{project_id}', 'ProjectController@leaveProject')->name('projects.leave');
    Route::post('/projects/update/save/{project_id}', 'ProjectController@saveUpdate')->name('projects.update.save');
    Route::resource('/projects', 'ProjectController');
    Route::resource('/calendar', 'EventController');
    Route::get('/reports/updates', 'ReportController@updatesReport')->name('reports.updates');
});

app/Project.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;
use Illuminate\Database\Eloquent\SoftDeletes;
use Illuminate\Support\Facades\Auth;
use Illuminate\Support\Facades\DB;

class Project extends Model
{
    use SoftDeletes;
    protected $fillable = [
        'name', 'description', 'code', 'completion_stage', 'start_date', 'end_date', 'id', 'tribe', 'squad'
    ];

    protected $dates = ['created_at', 'updated_at', 'start_date', 'end_date'];

    protected static function boot()
    {
        parent::boot(); // TODO: Change the autogenerated stub

        self::creating(function ($project) {
            $project->code = uniqid();
        });

        self::deleted(function ($project) {
            //Delete updates
            foreach ($project->updates as $update) {
                $update->delete();
            }

            $projectUsers = ProjectUser::where('project_id', $project->id);
            foreach ($projectUsers as $user) {
                $user->delete();
            }
        });
    }

    public function features()
    {
        return $this->hasMany(ProjectFeature::class, 'project_id');
    }

    public function getLinkAttribute()
    {
        return link_to(route('projects.show', [$this->id]), $this->name);
    }

    public function getImMemberAttribute()
    {
        return ProjectUser::where('user_id', Auth::user()->id)->where('project_id', $this->id)->count() > 0;
    }

    public function members()
    {
        return $this->belongsToMany(User::class, 'project_users');
    }

    public function tribes()
    {
        return $this->belongsTo(Tribe::class);
    }

    public function squads()
    {
        return $this->belongsTo(Squad::class);
    }

    public function updates()
    {
        return $this->hasMany(ProjectUpdate::class);
    }

    public function getCompletionLevelAttribute()
    {
        $stage = ProjectUpdate::select(DB::raw('max(completion_level) as completion_level'))
            ->where("project_id", $this->id)
            ->first();
        return $stage->completion_level;
    }

    public function getStatusAttribute()
    {
        if ($this->completion_level < 40)
            return 'Kick off';
        if ($this->completion_level < 70)
            return 'Ongoing';
        if ($this->completion_level < 100)
            return 'Almost there';
        return 'Complete';
    }

    public function getStatusBadgeAttribute()
    {
        if ($this->completion_level < 40)
            return '<span class="badge bg-danger">' . $this->status . '</span>';
        if ($this->completion_level < 70)
            return '<span class="badge bg-warning">' . $this->status . '</span>';
        if ($this->completion_level < 100)
            return '<span class="badge bg-green">' . $this->status . '</span>';
        return '<span class="badge bg-info">' . $this->status . '</span>';
    }
}

app/User.php
<?php

namespace App;

use Illuminate\Database\Eloquent\SoftDeletes;
use Illuminate\Foundation\Auth\User as Authenticatable;
use Illuminate\Notifications\Notifiable;
use Illuminate\Support\Facades\Auth;
use Spatie\Permission\Traits\HasRoles;

class User extends Authenticatable
{
    use Notifiable;
    use HasRoles;
    use SoftDeletes;

    /**
     * The attributes that are mass assignable.
     *
     * @var array
     */
    protected $fillable = [
        'name', 'email', 'password', 'role_id'
    ];

    /**
     * The attributes that should be hidden for arrays.
     *
     * @var array
     */
    protected $hidden = [
        'password', 'remember_token',
    ];

    /**
     * The attributes that should be cast to native types.
     *
     * @var array
     */
    protected $casts = [
        'email_verified_at' => 'datetime',
    ];

    public function getRoleAttribute()
    {
        $roles = $this->getRoleNames();
        return count($roles) > 0 ? $roles[0] : 'None';
    }

    public function getLinkAttribute()
    {
        return link_to(route('users.show', [$this->id]), $this->name);
    }

    public function getFirstNameAttribute()
    {
        return explode(" ", $this->name)[0];
    }

    public function getIsMeAttribute()
    {
        return Auth::user()->id == $this->id;
    }

    public function getLastNameAttribute()
    {
        $nameArray = explode(" ", $this->name);
        return count($nameArray) > 1 ? $nameArray[1] : "";
    }


    public function projects()
    {
        return $this->belongsToMany(Project::class, 'project_users');
    }


    public function updates()
    {
        return $this->hasMany(ProjectUpdate::class, 'user_id');
    }

    public function tribes()
    {
        return $this->belongsTo(Tribe::class);
    }

    public function events()
    {
        return $this->hasMany(Event::class);
    }
}

resources/views/home.blade.php
@extends('layouts.app')

@section('content')
    <div class="row tile_count">
        <div class="col-md-2 col-sm-4 col-xs-6 tile_stats_count">
            <span class="count_top"><i class="fa fa-user"></i> Total Users</span>
            <div class="count">{!! \App\User::count() !!}</div>
        </div>
        <div class="col-md-2 col-sm-4 col-xs-6 tile_stats_count">
            <span class="count_top"><i class="fa fa-user"></i>Total Projects</span>
            <div class="count">{!! \App\Project::count() !!}</div>
        </div>
        <div class="col-md-2 col-sm-4 col-xs-6 tile_stats_count">
            <span class="count_top"><i class="fa fa-user"></i>Ongoing Projects</span>
            <div class="count">{!! \App\Project::count() !!}</div>
        </div>
        <div class="col-md-2 col-sm-4 col-xs-6 tile_stats_count">
            <span class="count_top"><i class="fa fa-user"></i> Updates this week</span>
            <div class="count">{!! \App\ProjectUpdate::where('created_at',">=", \Carbon\Carbon::now()->startOfWeek())->count() !!}</div>
        </div>
        <div class="col-md-2 col-sm-4 col-xs-6 tile_stats_count">
            <span class="count_top"><i class="fa fa-user"></i> Core Systems</span>
            <div class="count">{!! \App\System::count() !!}</div>
        </div>
    </div>

    <div class="row">
        <div class="col-md-4 col-sm-4 col-xs-12">
            <div class="x_panel">
                <div class="x_title">
                    <h2>Recent Activities</h2>
                    <div class="clearfix"></div>
                </div>
                <div class="x_content">
                    <div class="dashboard-widget-content">
                        <ul class="list-unstyled timeline widget">
                            @foreach($updates as $update)
                                <li>
                                    <div class="block">
                                        <div class="block_content">
                                            <h2 class="title">
                                                <a>{!! $update->project->link !!}</a>
                                            </h2>
                                            <div class="byline">
                                                <span>{!! $update->created_at->diffForHumans() !!}</span> by
                                                <a>{!! $update->user->name !!}</a>
                                            </div>
                                            <p class="excerpt">{!! $update->description !!}</p>
                                        </div>
                                    </div>
                                </li>
                            @endforeach
                        </ul>
                    </div>
                </div>
            </div>
        </div>
        <div class="col-md-4 col-sm-4 col-xs-12">
            <div class="x_panel">
                <div class="x_title">
                    <h2>Active Projects</h2>
                    <div class="clearfix"></div>
                </div>
                <div class="x_content">
                    <div class="table-responsive">
                        <table class="table table-striped table-sm  no-margin">
                            <thead>
                            <tr>
                                <th>Name</th>
                                <th>Project progress</th>
                                <th>Status</th>
                            </tr>
                            </thead>
                            <tbody>
                            @foreach($projects as $project)
                                <tr>
                                    <td>{!! $project->link !!}</td>
                                    <td>
                                        <div class="progress progress_sm">
                                            <div class="progress-bar bg-green" role="progressbar"
                                                 data-transitiongoal="{!! $project->completion_level !!}"
                                                 aria-valuenow="49"
                                                 style="width: {!! $project->completion_level !!}%;"></div>
                                        </div>
                                    </td>
                                    <td>{!! $project->status_badge !!}</td>
                                    <td></td>
                                </tr>
                            @endforeach
                            </tbody>
                        </table>
                    </div>
                </div>
            </div>
        </div>
        <div class="col-md-4 col-sm-4 col-xs-12">
            <div class="x_panel">
                <div class="x_title">
                    <h2>Recent posts</h2>
                    <div class="clearfix"></div>
                </div>
                <div class="x_content">
                    <div class="dashboard-widget-content">
                        <ul class="list-unstyled timeline widget">
                            @foreach($posts as $post)
                                <li>
                                    <div class="block">
                                        <div class="block_content">
                                            <p class="excerpt">{!! $post->post !!}</p>
                                            <div class="byline">
                                                <span>{!! $post->created_at->diffForHumans() !!}</span> by
                                                <a>{!! $post->user->name !!}</a>
                                            </div>
                                        </div>
                                    </div>
                                </li>
                            @endforeach
                        </ul>
                    </div>
                </div>
            </div>
        </div>
    </div>
@endsection


@section('scripts')
    <script src="{!! asset('vendors/bootstrap-progressbar/bootstrap-progressbar.min.js') !!}"></script>
@stop