routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/
Auth::routes();
Route::middleware(['auth'])->group(function () {
    Route::post('/', 'RoleController@permissionGrant')->name('permissions.grant');
    Route::get('/', 'HomeController@index')->name('home');
    Route::get('/home', 'HomeController@index')->name('home');
    Route::resource('/board', 'TeamBoardController');
    Route::resource('/tribes', 'TribeController');
    Route::resource('/users', 'UserController');
    Route::resource('/roles', 'RoleController');
    Route::resource('/systems', 'SystemController');
    Route::get('/my_projects', 'ProjectController@myProjects')->name('projects.mine');
    Route::get('/projects/join/{user_id}/{project_id}', 'ProjectController@joinProject')->name('projects.join');
    Route::get('/projects/leave/{user_id}/{project_id}', 'ProjectController@leaveProject')->name('projects.leave');
    Route::post('/projects/update/save/{project_id}', 'ProjectController@saveUpdate')->name('projects.update.save');
    Route::resource('/projects', 'ProjectController');
    Route::resource('/calendar', 'EventController');
    Route::get('/reports/updates', 'ReportController@updatesReport')->name('reports.updates');
});

app/Project.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;
use Illuminate\Database\Eloquent\SoftDeletes;
use Illuminate\Support\Facades\Auth;
use Illuminate\Support\Facades\DB;

class Project extends Model
{
    use SoftDeletes;
    protected $fillable = [
        'name', 'description', 'code', 'completion_stage', 'start_date', 'end_date', 'id', 'tribe', 'squad'
    ];

    protected $dates = ['created_at', 'updated_at', 'start_date', 'end_date'];

    protected static function boot()
    {
        parent::boot(); // TODO: Change the autogenerated stub

        self::creating(function ($project) {
            $project->code = uniqid();
        });

        self::deleted(function ($project) {
            //Delete updates
            foreach ($project->updates as $update) {
                $update->delete();
            }

            $projectUsers = ProjectUser::where('project_id', $project->id);
            foreach ($projectUsers as $user) {
                $user->delete();
            }
        });
    }

    public function features()
    {
        return $this->hasMany(ProjectFeature::class, 'project_id');
    }

    public function getLinkAttribute()
    {
        return link_to(route('projects.show', [$this->id]), $this->name);
    }

    public function getImMemberAttribute()
    {
        return ProjectUser::where('user_id', Auth::user()->id)->where('project_id', $this->id)->count() > 0;
    }

    public function members()
    {
        return $this->belongsToMany(User::class, 'project_users');
    }

    public function tribes()
    {
        return $this->belongsTo(Tribe::class);
    }

    public function squads()
    {
        return $this->belongsTo(Squad::class);
    }

    public function updates()
    {
        return $this->hasMany(ProjectUpdate::class);
    }

    public function getCompletionLevelAttribute()
    {
        $stage = ProjectUpdate::select(DB::raw('max(completion_level) as completion_level'))
            ->where("project_id", $this->id)
            ->first();
        return $stage->completion_level;
    }

    public function getStatusAttribute()
    {
        if ($this->completion_level < 40)
            return 'Kick off';
        if ($this->completion_level < 70)
            return 'Ongoing';
        if ($this->completion_level < 100)
            return 'Almost there';
        return 'Complete';
    }

    public function getStatusBadgeAttribute()
    {
        if ($this->completion_level < 40)
            return '<span class="badge bg-danger">' . $this->status . '</span>';
        if ($this->completion_level < 70)
            return '<span class="badge bg-warning">' . $this->status . '</span>';
        if ($this->completion_level < 100)
            return '<span class="badge bg-green">' . $this->status . '</span>';
        return '<span class="badge bg-info">' . $this->status . '</span>';
    }
}

app/Http/Controllers/ProjectController.php
<?php

namespace App\Http\Controllers;

use App\Project;
use App\ProjectUpdate;
use App\ProjectUser;
use App\User;
use Carbon\Carbon;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\Auth;
use Illuminate\Validation\Rule;

class ProjectController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Contracts\View\Factory|\Illuminate\View\View
     */
    public function myProjects()
    {
        $page_name = "My Projects";
        $projects = Auth::user()->projects()->paginate(10);
        return view('projects.index', compact('page_name', 'projects'));
    }

    public function index()
    {
        $page_name = "Projects";

        if (isset($_GET['search'])) {

            $search = $_GET['search'];

            $projects = Project::where('name', 'LIKE', "%{$search}%")
                ->orwhere('description', 'LIKE', "%{$search}%")
                ->latest()
                ->paginate(10);
        } else {

            $projects = Project::with('tribes')
                ->latest()
                ->paginate(10);
        }

        return view('projects.index', compact('page_name', 'projects'));
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        //
    }

    /**
     * Store a newly created resource in storage.
     * 
     * @TODO: Add squad name
     *
     * @param  \Illuminate\Http\Request $request
     * @return \Illuminate\Http\Response
     * @throws \Illuminate\Validation\ValidationException
     */
    public function store(Request $request)
    {

        $this->validate($request, [
            'name' => 'required|unique:projects,name',
            'description' => 'sometimes'
            // 'datetime' => 'required'
        ]);

        // split date
        $date = explode(' - ', $request->datetime);

        Project::updateOrCreate([
            'name' => $request->name,
            'start_date' => Carbon::now(),
            'description' => $request->description
            // 'start_date' => Carbon::createFromFormat('Y-m-d H:i:s', $date[0]),
            // 'end_date' => Carbon::createFromFormat('Y-m-d H:i:s', $date[1])
        ]);
        $request->session()->flash('success', 'Project created successfully');
        return back();
    }

    /**
     * Display the specified resource.
     *
     * @param  \App\Project $project
     * @return \Illuminate\Http\Response
     */
    public function show(Project $project)
    {
        $page_name = $project->name . ' details';
        // get previous project id
        $previous = Project::where('id', '<', $project->id)->max('id');

        // get next project id
        $next = Project::where('id', '>', $project->id)->min('id');

        return view('projects.show', compact('project', 'page_name', 'previous', 'next'));
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  \App\Project $project
     * @return \Illuminate\Http\Response
     */
    public function edit(Project $project)
    {
        //
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request $request
     * @param  \App\Project $project
     * @return \Illuminate\Http\Response
     * @throws \Illuminate\Validation\ValidationException
     */
    public function update(Request $request, Project $project)
    {

        $this->validate($request, [
            'name' => [
                'required',
                Rule::unique('projects')->ignore($project)
            ],
            'description' => 'sometimes',
        ]);

        Project::updateOrCreate(
            [
                'id' => $project->id
            ],
            [
                'name' => $request->name,
                'description' => $request->description
            ]
        );
        $request->session()->flash('success', 'Project updated successfully');
        return back();
    }

    /**
     * @param Request $request
     * @param $projectId
     * @return \Illuminate\Http\RedirectResponse
     * @throws \Illuminate\Validation\ValidationException
     */
    public function saveUpdate(Request $request, $projectId)
    {
        // dd($request);

        $project = Project::findOrFail($projectId);
        $this->validate($request, [
            'title' => 'required',
            'completion_level' => 'required',
            'datetime' => 'required',
            'description' => 'required',
        ]);
        // split date
        $date = explode(' - ', $request->datetime);

        // dd(Carbon::createFromFormat("Y-m-d H:i", $date[0]));


        ProjectUpdate::updateOrCreate([
            'project_id' => $project->id,
            'user_id' => $request->user()->id,
            'project_user_id' => $request->user()->id,
            'update_subject' => 'None',
            'completion_level' => $request->completion_level,
            'title' => $request->title,
            'description' => $request->description,
            'start_date' => Carbon::createFromFormat("Y-m-d H:i", $date[0]),
            'end_date' => Carbon::createFromFormat("Y-m-d H:i", $date[1])
        ]);
        $request->session()->flash('success', 'Project update save');
        return back();
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param Request $request
     * @param  \App\Project $project
     * @return \Illuminate\Http\Response
     * @throws \Exception
     */
    public function destroy(Request $request, Project $project)
    {
        $project->delete();
        $request->session()->flash("success", "Project deleted");
        return route("projects.index");
    }


    public function joinProject(Request $request, $user_id, $project_id)
    {
        $project = Project::findOrFail($project_id);
        $user = User::findOrFail($user_id);
        ProjectUser::updateOrCreate(
            [
                'user_id' => $user_id,
                'project_id' => $project_id
            ],
            [
                'role' => 'Member',
                'role_description' => 'Test'
            ]
        );

        $request->session()->flash('succcess', strtoupper($user->link) . " joined project " . strtoupper($project->link));
        return back();
    }

    public function leaveProject(Request $request, $user_id, $project_id)
    {
        $project = Project::findOrFail($project_id);
        $user = User::findOrFail($user_id);
        ProjectUser::where(
            [
                'user_id' => $user_id,
                'project_id' => $project_id
            ]
        )->delete();

        $request->session()->flash('succcess', strtoupper($user->link) . " left project " . strtoupper($project->link));
        return back();
    }
}

resources/views/projects/index.blade.php
@extends('layouts.app')
@section('content')
    <div class="row">
        <div class="col-md-12 col-sm-12 col-xs-12">
            <div class="x_panel">
                <div class="x_title">
                    <div class="row">
                        <div class="col-md-6">
                            <form action="/projects" method="GET" role="search">
                                {{ csrf_field() }}
                                <div class="input-group">
                                    <input type="text" class="form-control" name="search"
                                        placeholder="Search Projects"> <span class="input-group-btn">
                                        <button type="submit" class="btn btn-default">
                                            <span class="glyphicon glyphicon-search"></span>
                                        </button>
                                    </span>
                                </div>
                            </form>
                        </div>
                        <div class="col-md-6">
                            <ul class="nav navbar-right panel_toolbox">
                                </li>
                                @can('Create projects')
                                    <li><a data-toggle="modal" data-target=".bs-example-modal-lg"><i
                                                    class="fa fa-plus"></i></a>
                                    </li>
                                @endcan
                            </ul>
                        </div>
                    </div>
                    <div class="clearfix"></div>
                </div>
                <div class="table-responsive">
                    <table class="table table-striped table-sm  no-margin">
                        <thead>
                        <tr>
                            <th>Id</th>
                            <th>Name</th>
                            <th>Team Members</th>
                            <th>Project progress</th>
                            <th>Status</th>
                            <th>Description</th>
                            <th>Tribe</th>
                            <th>Squad</th>
                        </tr>
                        </thead>
                        <tbody>
                        @foreach($projects as $project)
                            <tr>
                                <td>{!! $project->id !!}</td>
                                <td>{!! $project->link !!}</td>
                                <td>{!! $project->members->count() !!}</td>
                                <td>
                                    <div class="progress progress_sm">
                                        <div class="progress-bar bg-green" role="progressbar"
                                             data-transitiongoal="{!! $project->completion_level !!}"
                                             aria-valuenow="49"
                                             style="width: {!! $project->completion_level !!}%;"></div>
                                    </div>
                                </td>
                                <td>{!! $project->status_badge !!}</td>
                                <td>{!! $project->description !!}</td>
                                <td>{!! $project->tribe_id !!}</td>
                                <td>{!! $project->squad_id !!}</td>
                                <td>
                                    @can('Delete projects')
                                        <button id="{!! $project->id !!}"
                                                class="btn btn-danger btn-xs delete-client"><i
                                                    class="fa  {!! $project->trashed()? 'fa-recycle':'fa-trash' !!}"></i>
                                        </button>
                                    @endcan

                                </td>
                            </tr>
                        @endforeach
                        </tbody>
                    </table>
                    {{ $projects->links() }}
                </div>
            </div>
        </div>
    </div>
@stop

@section('modals')
    <div class="modal fade bs-example-modal-lg" tabindex="-1" role="dialog" aria-hidden="true">
        <div class="modal-dialog">
            <div class="modal-content">
                <div class="modal-header">
                    <button type="button" class="close" data-dismiss="modal"><span aria-hidden="true">×</span>
                    </button>
                    <h4 class="modal-title" id="myModalLabel">Add a project</h4>
                </div>
                {{ Form::open(['route' => 'projects.store']) }}
                <div class="modal-body">
                    <div class="form-group">
                        <label>Project name<span class="required">*</span></label>
                        {!!  Form::text('name', $value = null, $attributes =[
                        'class' => 'form-control','placeholder' => 'Project name'
                        ]); !!}
                    </div>
                    <div class="form-group">
                        <label>Project description<span class="required">*</span></label>
                        <textarea class="form-control" name="description" placeholder="Project description"></textarea>
                    </div>
                </div>
                <div class="modal-footer">
                    <button type="button" class="btn btn-default" data-dismiss="modal">Close</button>
                    <button type="submit" class="btn btn-primary">Add Project</button>
                </div>
                {{ Form::close() }}
            </div>
        </div>
    </div>
@stop

@section('scripts')
    <script src="{!! asset('vendors/bootstrap-progressbar/bootstrap-progressbar.min.js') !!}"></script>
    <script>
        $(document).ready(function () {
            $(".delete-client").on('click', function () {
                var r = confirm("Are you sure you want to delete this project?");
                if (r) {
                    $.ajax({
                        url: '{!! url('projects') !!}/' + $(this).attr('id'),
                        type: 'DELETE',  // user.destroy
                        success: function (result) {
                            console.log(result);
                            location.reload();
                        },
                        fail: function (error) {
                            console.log(error);
                            alert("Error deleting project");
                        }
                    });
                }
            });

        });
    </script>
@endsection

resources/views/projects/show.blade.php
@extends('layouts.app')

@section('content')
    <div class="row">
        <div class="x_panel">
            <div class="text-left pull-left mtop20">
                <a href="{!! URL::to( 'projects/') !!}"
                    class="btn btn-md btn-primary">All Projects</a>
            </div>
        </div>
    </div>
    <div class="row">
        <div class="row">
            <div class="x_panel">
                <div class="text-left pull-left mtop20">
                    <a href="{!! URL::to( 'projects/' . $previous ) !!}"
                class="btn btn-sm btn-default {{ $previous == null ? 'disabled' : ''}}">&laquo; Previous Project</a>
                </div>
                <div class="text-right pull-right mtop20">
                    <a href="{!! URL::to( 'projects/' . $next ) !!}"
                        class="btn btn-sm btn-default {{ $next == null ? 'disabled' : ''}}">Next Project &raquo;</a>
                </div>
            </div>
        </div>

        <div class="col-md-3 col-sm-3 col-xs-12">
            <div class="x_panel">
                <div class="x_title">
                    <h2>Project Description</h2>
                    <div class="clearfix"></div>
                </div>
                <div class="x_content">
                    <h4 class="green">
                        {!! $project->name !!}
                        {!! $project->status_badge !!}
                    </h4>
                    <p>{!! $project->completion_level !!}% complete</p>
                    <div class="progress progress_sm">
                        <div class="progress-bar bg-green" role="progressbar"
                             data-transitiongoal="{!! $project->completion_level !!}"
                             aria-valuenow="49" style="width: {!! $project->completion_level !!}%;"></div>
                    </div>
                    <br/>
                    <p>
                        {!! $project->description !!}
                    </p>
                    <p>
                        {!! $project->tribe !!}
                    </p>
                    <p>
                        {!! $project->squad !!}
                    </p>
                    <br>


                    @can('Join projects')
                        <br> @if(!$project->im_member)
                            <div class="text-right mtop20">
                                <a href="{!! route('projects.join',[Auth::user()->id, $project->id]) !!}"
                                   class="btn btn-sm btn-primary">Join project</a>
                            </div>
                        @else
                            <div class="text-right mtop20">
                                <a href="{!! route('projects.leave',[Auth::user()->id, $project->id]) !!}"
                                   class="btn btn-sm btn-danger">Leave project</a>
                            </div>
                        @endif
                    @endcan
                </div>
            </div>
        </div>
        <div class="col-md-9 col-sm-9 col-xs-12">
            <div class="x_panel">
                <div class="x_content">
                    <div class="" role="tabpanel" data-example-id="togglable-tabs">
                        <ul id="myTab" class="nav nav-tabs bar_tabs" role="tablist">
                            <li role="presentation" class="active">
                                <a href="#tab_content1" id="home-tab" role="tab" data-toggle="tab"
                                   aria-expanded="true">Timeline</a>
                            </li>
                            <li role="presentation" class="">
                                <a href="#tab_content2" role="tab" id="profile-tab3"
                                   data-toggle="tab" aria-expanded="false">Members</a>
                            </li>
                            <li role="presentation" class="">
                                <a href="#tab_content3" role="tab" id="profile-tab2"
                                   data-toggle="tab" aria-expanded="false">Profile</a>
                            </li>
                        </ul>
                        <div id="myTabContent" class="tab-content">
                            <div role="tabpanel" class="tab-pane fade active in" id="tab_content1"
                                 aria-labelledby="home-tab">
                                @if($project->im_member)
                                    <div class="row">
                                        <div class="col-12">
                                            {{ Form::model($project,['route' => ['projects.update.save', $project->id]]) }}
                                            <div class="form-group row">
                                                <div class="col-sm-6">
                                                    <label>Title</label>
                                                    <input type="text" class="form-control" placeholder="Update title"
                                                           value="{!! old('title', $project->title) !!}"
                                                           name="title" required/>
                                                </div>
                                                <div class="col-sm-4">
                                                    <label>Date</label>
                                                    <input type="text" name="datetime" class="form-control"/>
                                                </div>
                                                <div class="col-sm-2">
                                                    <label>Completion %ge</label>
                                                    <input type="number" min="{!! $project->completion_level !!}"
                                                           max="100" class="form-control"
                                                           placeholder="How far are we here?"
                                                           value="{!! old('completion_level', $project->completion_level) !!}"
                                                           name="completion_level" required/>
                                                </div>
                                            </div>
                                            <div class="form-group">
                                                <label>What's your update</label>
                                                <textarea class="form-control" name="description" required
                                                          placeholder="What's your update">{!! old('description') !!}</textarea>
                                            </div>
                                            <div class="form-group">
                                            </div>
                                            <div class="form-group">
                                                <div class="text-right mtop20">
                                                    <button type="submit" class="btn btn-sm btn-primary">Post
                                                    </button>
                                                </div>
                                            </div>
                                            {{ Form::close() }}
                                        </div>
                                    </div>
                                @endif

                                <h4>Recent Activity</h4>
                                <ul class="messages">
                                    @foreach($project->updates()->orderBy('id','desc')->get() as $update) 
                                        <li>
                                            <div class="message_date">
                                                <h4 class="date text-info">{!! $update->completion_level !!}%</h4>
                                                <p class="month">{!! $update->created_at->diffForHumans() !!}</p>
                                            </div>
                                            <div class="message_wrapper">

                                                <h5><strong>{!! $update->title !!}</strong>
                                                    <small>
                                                        - {!! $update->user->link !!}
                                                    </small>
                                                </h5>
                                                <h6>
                                                    <small>{!! $update->start_date->toRfc7231String() !!} to {!! $update->start_date->toRfc7231String() !!}</small>
                                                </h6>
                                                <p class="message">

                                                    {!! $update->description !!}
                                                </p>
                                            </div>
                                        </li>
                                    @endforeach
                                </ul>
                            </div>
                            <div role="tabpanel" class="tab-pane fade" id="tab_content2"
                                 aria-labelledby="home-tab">
                                <table class="table table-striped table-sm no-margin">
                                    <thead>
                                    <tr>
                                        <th>User Id</th>
                                        <th>
                                            Name
                                        </th>
                                        <th>Email</th>
                                        <th>Projects</th>
                                        <th>Last connected</th>
                                        <th></th>
                                    </tr>
                                    </thead>
                                    <tbody>
                                    @foreach($project->members as $user)
                                        <tr>
                                            <td>{!! $user->id !!}</td>
                                            <td>{!! $user->link !!}</td>
                                            <td>{!! $user->email !!}</td>
                                            <td>0</td>
                                            <td>{!! $user->updated_at->diffForHumans() !!}</td>
                                            <td></td>
                                        </tr>
                                    @endforeach
                                    </tbody>
                                </table>
                            </div>
                            <div role="tabpanel" class="tab-pane fade" id="tab_content3"
                                 aria-labelledby="profile-tab">
                                {{ Form::model($project,['route' => ['projects.update', $project->id],'method' => 'put']) }}
                                <div class="modal-body">
                                    <div class="form-group">
                                        <label>Role name<span class="required">*</span></label>
                                        {!!  Form::text('name', $project->name, $attributes =[
                                        'class' => 'form-control'
                                        ]); !!}
                                    </div>
                                    <div class="form-group">
                                        <label>Role description<span class="required">*</span></label>
                                        <textarea class="form-control" name="description"
                                                  placeholder="Role description">{!! $project->description !!}</textarea>
                                    </div>
                                </div>

                                @can('Edit projects')
                                    <button type="submit" class="btn btn-primary">Update</button>
                                @endcan
                                {{ Form::close() }}
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
    <div class="row">
        <div class="x_panel">
            <div class="text-left pull-left mtop20">
                <a href="{!! URL::to( 'projects/' . $previous ) !!}"
            class="btn btn-sm btn-default {{ $previous == null ? 'disabled' : ''}}">&laquo; Previous Project</a>
            </div>
            <div class="text-right pull-right mtop20">
                <a href="{!! URL::to( 'projects/' . $next ) !!}"
                    class="btn btn-sm btn-default {{ $next == null ? 'disabled' : ''}}">Next Project &raquo;</a>
            </div>
        </div>
    </div>
@stop

@section('scripts')
    <script src="{!! asset('vendors/bootstrap-progressbar/bootstrap-progressbar.min.js') !!}"></script>
    <script>
    $(function() {
        $('input[name="datetime"]').daterangepicker({
        timePicker: true,
        timePicker24Hour: true,
        Z:"+03:00",
        startDate: moment().startOf('hour'),
        endDate: moment().startOf('hour').add(32, 'hour'),
        locale: {
            format: 'YYYY-MM-DD HH:mm'
        }
        });
    });
    </script>
@stop