routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/
Auth::routes();
Route::middleware(['auth'])->group(function () {
    Route::post('/', 'RoleController@permissionGrant')->name('permissions.grant');
    Route::get('/', 'HomeController@index')->name('home');
    Route::get('/home', 'HomeController@index')->name('home');
    Route::resource('/board', 'TeamBoardController');
    Route::resource('/tribes', 'TribeController');
    Route::resource('/users', 'UserController');
    Route::resource('/roles', 'RoleController');
    Route::resource('/systems', 'SystemController');
    Route::get('/my_projects', 'ProjectController@myProjects')->name('projects.mine');
    Route::get('/projects/join/{user_id}/{project_id}', 'ProjectController@joinProject')->name('projects.join');
    Route::get('/projects/leave/{user_id}/{project_id}', 'ProjectController@leaveProject')->name('projects.leave');
    Route::post('/projects/update/save/{project_id}', 'ProjectController@saveUpdate')->name('projects.update.save');
    Route::resource('/projects', 'ProjectController');
    Route::resource('/calendar', 'EventController');
    Route::get('/reports/updates', 'ReportController@updatesReport')->name('reports.updates');
});

app/Project.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;
use Illuminate\Database\Eloquent\SoftDeletes;
use Illuminate\Support\Facades\Auth;
use Illuminate\Support\Facades\DB;

class Project extends Model
{
    use SoftDeletes;
    protected $fillable = [
        'name', 'description', 'code', 'completion_stage', 'start_date', 'end_date', 'id', 'tribe', 'squad'
    ];

    protected $dates = ['created_at', 'updated_at', 'start_date', 'end_date'];

    protected static function boot()
    {
        parent::boot(); // TODO: Change the autogenerated stub

        self::creating(function ($project) {
            $project->code = uniqid();
        });

        self::deleted(function ($project) {
            //Delete updates
            foreach ($project->updates as $update) {
                $update->delete();
            }

            $projectUsers = ProjectUser::where('project_id', $project->id);
            foreach ($projectUsers as $user) {
                $user->delete();
            }
        });
    }

    public function features()
    {
        return $this->hasMany(ProjectFeature::class, 'project_id');
    }

    public function getLinkAttribute()
    {
        return link_to(route('projects.show', [$this->id]), $this->name);
    }

    public function getImMemberAttribute()
    {
        return ProjectUser::where('user_id', Auth::user()->id)->where('project_id', $this->id)->count() > 0;
    }

    public function members()
    {
        return $this->belongsToMany(User::class, 'project_users');
    }

    public function tribes()
    {
        return $this->belongsTo(Tribe::class);
    }

    public function squads()
    {
        return $this->belongsTo(Squad::class);
    }

    public function updates()
    {
        return $this->hasMany(ProjectUpdate::class);
    }

    public function getCompletionLevelAttribute()
    {
        $stage = ProjectUpdate::select(DB::raw('max(completion_level) as completion_level'))
            ->where("project_id", $this->id)
            ->first();
        return $stage->completion_level;
    }

    public function getStatusAttribute()
    {
        if ($this->completion_level < 40)
            return 'Kick off';
        if ($this->completion_level < 70)
            return 'Ongoing';
        if ($this->completion_level < 100)
            return 'Almost there';
        return 'Complete';
    }

    public function getStatusBadgeAttribute()
    {
        if ($this->completion_level < 40)
            return '<span class="badge bg-danger">' . $this->status . '</span>';
        if ($this->completion_level < 70)
            return '<span class="badge bg-warning">' . $this->status . '</span>';
        if ($this->completion_level < 100)
            return '<span class="badge bg-green">' . $this->status . '</span>';
        return '<span class="badge bg-info">' . $this->status . '</span>';
    }
}

app/User.php
<?php

namespace App;

use Illuminate\Database\Eloquent\SoftDeletes;
use Illuminate\Foundation\Auth\User as Authenticatable;
use Illuminate\Notifications\Notifiable;
use Illuminate\Support\Facades\Auth;
use Spatie\Permission\Traits\HasRoles;

class User extends Authenticatable
{
    use Notifiable;
    use HasRoles;
    use SoftDeletes;

    /**
     * The attributes that are mass assignable.
     *
     * @var array
     */
    protected $fillable = [
        'name', 'email', 'password', 'role_id'
    ];

    /**
     * The attributes that should be hidden for arrays.
     *
     * @var array
     */
    protected $hidden = [
        'password', 'remember_token',
    ];

    /**
     * The attributes that should be cast to native types.
     *
     * @var array
     */
    protected $casts = [
        'email_verified_at' => 'datetime',
    ];

    public function getRoleAttribute()
    {
        $roles = $this->getRoleNames();
        return count($roles) > 0 ? $roles[0] : 'None';
    }

    public function getLinkAttribute()
    {
        return link_to(route('users.show', [$this->id]), $this->name);
    }

    public function getFirstNameAttribute()
    {
        return explode(" ", $this->name)[0];
    }

    public function getIsMeAttribute()
    {
        return Auth::user()->id == $this->id;
    }

    public function getLastNameAttribute()
    {
        $nameArray = explode(" ", $this->name);
        return count($nameArray) > 1 ? $nameArray[1] : "";
    }


    public function projects()
    {
        return $this->belongsToMany(Project::class, 'project_users');
    }


    public function updates()
    {
        return $this->hasMany(ProjectUpdate::class, 'user_id');
    }

    public function tribes()
    {
        return $this->belongsTo(Tribe::class);
    }

    public function events()
    {
        return $this->hasMany(Event::class);
    }
}

app/Http/Controllers/UserController.php
<?php

namespace App\Http\Controllers;

use App\User;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\Hash;
use Spatie\Permission\Models\Role;

class UserController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $page_name = 'Users';
        $users = User::paginate(10);
        $roles = Role::all();
        return view('users.index', compact('users', 'page_name', 'roles'));
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        //
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param \Illuminate\Http\Request $request
     * @return \Illuminate\Http\RedirectResponse
     * @throws \Illuminate\Validation\ValidationException
     */
    public function store(Request $request)
    {
        $this->validate($request, [
            'first_name' => 'required',
            'last_name' => 'required',
            'email' => 'required',
            'role' => 'required|exists:roles,id',
            'password' => 'required',
        ]);
        $user = User::updateOrCreate(
            [
                'email' => $request->email
            ],
            [
                'role_id' => 1,
                'name' => $request->first_name . " " . $request->last_name,
                'password' => Hash::make($request->password)
            ]
        );

        $role = Role::find($request->role);
        $user->assignRole($role);
        $request->session()->flash('success', 'User account created');
        return back();
    }

    /**
     * Display the specified resource.
     *
     * @param \App\User $user
     * @return \Illuminate\Http\Response
     */
    public function show(User $user)
    {
        $page_name = $user->name . ' Profile';
        $roles = Role::all();
        return view('users.show', compact('user', 'page_name', 'roles'));
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param \App\User $system
     * @return \Illuminate\Http\Response
     */
    public function edit(User $system)
    {
        //
    }

    /**
     * Update the specified resource in storage.
     *
     * @param \Illuminate\Http\Request $request
     * @param User $user
     * @return \Illuminate\Http\Response
     * @throws \Illuminate\Validation\ValidationException
     */
    public function update(Request $request, User $user)
    {
        $this->validate($request, [
            'first_name' => 'required',
            'last_name' => 'required',
            'email' => 'required',
            'role' => 'required|exists:roles,id',
            'password' => 'required',
        ]);
        $user = User::updateOrCreate(
            [
                'id' => $user->id
            ],
            [
                'role_id' => 1,
                'email' => $request->email,
                'name' => $request->first_name . " " . $request->last_name,
                'password' => Hash::make($request->password)
            ]
        );

        if ($user->role != 'None')
            $user->removeRole($user->role);

        $role = Role::find($request->role);
        $user->assignRole($role);
        $request->session()->flash('success', 'User account updated');
        return back();
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param Request $request
     * @param User $user
     * @return void
     * @throws \Exception
     */
    public function destroy(Request $request, User $user)
    {
        $user->delete();
        $request->session()->flash('success', 'User account deleted');
        return back();
    }
}

resources/views/users/index.blade.php
@extends('layouts.app')

@section('content')
    <div class="row">
        <div class="col-md-12 col-sm-12 col-xs-12">
            <div class="x_panel">
                <div class="x_title">
                    <h2>Portal users</h2>
                    <ul class="nav navbar-right panel_toolbox">
                        <li><a class="collapse-link"><i class="fa fa-chevron-up"></i></a>
                        </li>

                        @can('Create users')
                            <li><a data-toggle="modal" data-target=".bs-example-modal-lg"><i
                                            class="fa fa-user-plus"></i></a>
                            </li>
                        @endcan
                    </ul>
                    <div class="clearfix"></div>
                </div>
                <div class="x_content">
                    <div class="table-responsive">
                        <table class="table table-striped table-sm">
                            <thead>
                            <tr>
                                <th>User Id</th>
                                <th>
                                    Name
                                </th>
                                <th>Email</th>
                                <th>Role</th>
                                <th>Projects</th>
                                <th>Last connected</th>
                                <th></th>
                            </tr>
                            </thead>
                            <tbody>
                            @foreach($users as $user)
                                <tr>
                                    <td>{!! $user->id !!}</td>
                                    <td>{!! $user->link !!}</td>
                                    <td>{!! $user->email !!}</td>
                                    <td>{!! $user->role !!}</td>
                                    <td>0</td>
                                    <td>{!! $user->updated_at->diffForHumans() !!}</td>
                                    <td></td>
                                </tr>
                            @endforeach
                            </tbody>
                        </table>
                        {{ $users->links() }}
                    </div>
                </div>
            </div>
        </div>
    </div>
@stop

@section('modals')
    @can('Create users')
        <div class="modal fade bs-example-modal-lg" tabindex="-1" role="dialog" aria-hidden="true">
            <div class="modal-dialog">
                <div class="modal-content">

                    <div class="modal-header">
                        <button type="button" class="close" data-dismiss="modal"><span aria-hidden="true">×</span>
                        </button>
                        <h4 class="modal-title" id="myModalLabel">Create user</h4>
                    </div>
                    {{ Form::open(['route' => 'users.store']) }}
                    <div class="modal-body">
                        <div class="form-group row">
                            <div class="col-sm-6">
                                <label>First Name<span class="required">*</span></label>
                                {!!  Form::text('first_name', $value = null, $attributes =[
                                'class' => 'form-control'
                                ]); !!}
                            </div>
                            <div class="col-sm-6">
                                <label>Last Name<span class="required">*</span></label>
                                {!!  Form::text('last_name', $value = null, $attributes =[
                                'class' => 'form-control'
                                ]); !!}
                            </div>
                        </div>
                        <div class="form-group">
                            <label>Role<span class="required">*</span></label>
                            <select class="form-control" name="role">
                                @foreach($roles as $role)
                                    <option value="{!! $role->id !!}">{!! $role->name !!}</option>
                                @endforeach
                            </select>
                        </div>
                        <div class="form-group">
                            <label>Email address<span class="required">*</span></label>
                            {!!  Form::email('email', $value = null, $attributes =[
                            'class' => 'form-control'
                            ]); !!}
                        </div>
                        <div class="form-group">
                            <label>Set Password<span class="required">*</span></label>
                            {!!  Form::password( $value = null, $attributes =['name'=>'password',
                            'class' => 'form-control'
                            ]); !!}
                        </div>
                    </div>
                    <div class="modal-footer">
                        <button type="button" class="btn btn-default" data-dismiss="modal">Close</button>
                        <button type="submit" class="btn btn-primary">Create User</button>
                    </div>
                    {{ Form::close() }}
                </div>
            </div>
        </div>
    @endcan
@stop

resources/views/users/show.blade.php
@extends('layouts.app')

@section('content')
    <div class="row">
        <div class="col-md-12 col-sm-12 col-xs-12">
            <div class="x_panel">
                <div class="x_title">
                    <h2>{!! $user->name !!}
                        <small>Profile details</small>
                    </h2>

                    <div class="clearfix"></div>
                </div>
                <div class="x_content">
                    <div class="col-md-3 col-sm-3 col-xs-12 profile_left">
                        <h3>{!! $user->name !!}</h3>

                        <ul class="list-unstyled user_data">
                            <li><i class="fa fa-envelope user-profile-icon"></i>
                                {!! $user->email !!}
                            </li>

                            <li>
                                <i class="fa fa-briefcase user-profile-icon"></i> VAS Engineer
                            </li>
                        </ul>
                        @if(Gate::check('Edit users') || $user->is_me)
                            <a class="btn btn-success" data-toggle="modal" data-target=".bs-example-modal-lg"><i
                                        class="fa fa-edit m-right-xs"></i>Edit Profile</a>
                        @endif
                        <br/>


                    </div>
                    <div class="col-md-9 col-sm-9 col-xs-12">
                        <div class="" role="tabpanel" data-example-id="togglable-tabs">
                            <ul id="myTab" class="nav nav-tabs bar_tabs" role="tablist">
                                <li role="presentation" class="active">
                                    <a href="#tab_content1" id="home-tab" role="tab" data-toggle="tab"
                                       aria-expanded="true">Recent activities</a>
                                </li>
                                <li role="presentation" class="">
                                    <a href="#tab_content2" role="tab" id="profile-tab"
                                       data-toggle="tab" aria-expanded="false">Projects</a>
                                </li>
                            </ul>
                            <div id="myTabContent" class="tab-content">
                                <div role="tabpanel" class="tab-pane fade active in" id="tab_content1"
                                     aria-labelledby="home-tab">

                                    <ul class="messages">
                                        @foreach($user->updates as $update)
                                            <li>
                                                <div class="message_date">
                                                    <h4 class="date text-info">{!! $update->completion_level !!}%</h4>
                                                    <p class="month">{!! $update->created_at->diffForHumans() !!}</p>
                                                </div>
                                                <div class="message_wrapper">

                                                    <h5><strong>{!! $update->title !!}</strong>
                                                        <small>
                                                            - {!! $update->user->link !!}
                                                        </small>
                                                    </h5>
                                                    <p class="message">
                                                        {!! $update->description !!}
                                                        <br/>
                                                        -
                                                        <small>{!! $update->project->link !!}</small>
                                                    </p>
                                                </div>
                                            </li>
                                        @endforeach
                                    </ul>
                                </div>
                                <div role="tabpanel" class="tab-pane fade" id="tab_content2"
                                     aria-labelledby="profile-tab">

                                    <table class="table table-striped table-sm  no-margin">
                                        <thead>
                                        <tr>
                                            <th>Id</th>
                                            <th>Name</th>
                                            <th>Team Members</th>
                                            <th>Project progress</th>
                                            <th>Status</th>
                                            <th>Description</th>
                                        </tr>
                                        </thead>
                                        <tbody>
                                        @foreach($user->projects as $project)
                                            <tr>
                                                <td>{!! $project->id !!}</td>
                                                <td>{!! $project->link !!}</td>
                                                <td>{!! $project->members->count() !!}</td>
                                                <td>
                                                    <div class="progress progress_sm">
                                                        <div class="progress-bar bg-green" role="progressbar"
                                                             data-transitiongoal="{!! $project->completion_level !!}"
                                                             aria-valuenow="49"
                                                             style="width: {!! $project->completion_level !!}%;"></div>
                                                    </div>
                                                </td>
                                                <td>{!! $project->status_badge !!}</td>
                                                <td>{!! $project->description !!}</td>
                                                <td></td>
                                            </tr>
                                        @endforeach
                                        </tbody>
                                    </table>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
@stop

@section('modals')
    @if(Gate::check('Edit users') || $user->is_me)
        <div class="modal fade bs-example-modal-lg" tabindex="-1" role="dialog" aria-hidden="true">
            <div class="modal-dialog">
                <div class="modal-content">
                    <div class="modal-header">
                        <button type="button" class="close" data-dismiss="modal"><span aria-hidden="true">×</span>
                        </button>
                        <h4 class="modal-title" id="myModalLabel">Edit {!! $user->name !!}</h4>
                    </div>
                    {{ Form::model($user,['route' => ['users.update', $user->id],'method' => 'put']) }}

                    <div class="modal-body">
                        <div class="form-group row">
                            <div class="col-sm-6">
                                <label>First Name<span class="required">*</span></label>
                                {!!  Form::text('first_name', $value = $user->first_name, $attributes =[
                                'class' => 'form-control'
                                ]); !!}
                            </div>
                            <div class="col-sm-6">
                                <label>Last Name<span class="required">*</span></label>
                                {!!  Form::text('last_name', $value = $user->last_name, $attributes =[
                                'class' => 'form-control'
                                ]); !!}
                            </div>
                        </div>

                        <div class="form-group">
                            <label>Role<span class="required">*</span></label>
                            <select class="form-control" name="role">
                                @foreach($roles as $role)
                                    <option {!! $user->role == $role->name ? 'selected':'' !!} value="{!! $role->id !!}">{!! $role->name !!}</option>
                                @endforeach
                            </select>
                        </div>
                        <div class="form-group">
                            <label>Email address<span class="required">*</span></label>
                            {!!  Form::email('email', $value = $user->email, $attributes =[
                            'class' => 'form-control'
                            ]); !!}
                        </div>
                        @can('Reset user password')
                            @if(!$user->is_me)
                                <div class="form-group">
                                    <label>Set New Password<span class="required">*</span></label>
                                    {!!  Form::password( $value = null, $attributes =['name'=>'password',
                                    'class' => 'form-control'
                                    ]); !!}
                                </div>
                            @endif
                        @endcan
                        @if($user->is_me)
                            <div class="form-group">
                                <label>Reset Password<span class="required">*</span></label>
                                {!!  Form::password( $value = null, $attributes =['name'=>'password',
                                'class' => 'form-control'
                                ]); !!}
                            </div>
                        @endif
                    </div>
                    <div class="modal-footer">
                        <button type="button" class="btn btn-default" data-dismiss="modal">Close</button>
                        <button type="submit" class="btn btn-primary">Update</button>
                    </div>
                    {{ Form::close() }}
                </div>
            </div>
        </div>
    @endif
@stop

@section('styles')
    <link href="{!! asset('vendors/bootstrap-daterangepicker/daterangepicker.css') !!}" rel="stylesheet">
@stop
@section('scripts')
    <script src="{!! asset('/vendors/raphael/raphael.min.js') !!}"></script>
    <script src="{!! asset('/vendors/morris.js/morris.min.js') !!}"></script>
    <!-- bootstrap-progressbar -->
    <script src="{!! asset('/vendors/bootstrap-progressbar/bootstrap-progressbar.min.js') !!}"></script>
    <!-- bootstrap-daterangepicker -->
    <script src="{!! asset('/vendors/moment/min/moment.min.js') !!}"></script>
    <script src="{!! '/vendors/bootstrap-daterangepicker/daterangepicker.js' !!}"></script>

@stop